### ISSUE TITLE
2 projects

### ISSUE THREAD

**Issue by markolofsen** [chenjr0719/Docker-Django-Nginx-MySQL#1]
How to use two different django-projects with same IP and two different docker-containers?

**Comment by chenjr0719** [comment]
The simplest way is:
```shell
sudo docker run -itd -p 80:80 -v $PROJECET1_DIR:/home/django/website chenjr0719/django-nginx-mysql
sudo docker run -itd -p 81:80 -v $PROJECET2_DIR:/home/django/website chenjr0719/django-nginx-mysql
```

This will host two docker container with two different port with the same IP.

If you want to use the same IP with same port, considering to use `subdomain` and `reverse proxy` with `Nginx`. You can take a look at my [post](https://chenjr-jacob.idv.tw/2016/10/nginx-application-subdomain-virtual-host-reverse-proxy/).

**Comment by markolofsen** [comment]
thanks
